
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
default_stages: [commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: debug-statements
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    verbose: true
    entry: bash -c 'mypy "$@" || true'
    args: [--ignore-missing-imports]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.6
  hooks:
    - id: ruff
      args: [ --fix, --select, I]
    - id: ruff-format
